# CI and PR build script for language-service and language-server

trigger:
- master
- releases/*

jobs:
- template: build-package.yml
  parameters:
    name: 'build_language_service'
    root: 'language-service'
    packagename: 'azure-pipelines-language-service'

- template: build-package.yml
  parameters:
    name: 'build_language_server'
    root: 'language-server'
    packagename: 'azure-pipelines-language-server'
